apiVersion: v1
kind: Pod
metadata:
 name: test-pd
spec: 
 containers:
  - name: nginx
    image: nginx
    volumeMounts:
     - name: nginx-logs
       mountPath: /var/log/nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","2000"]
    volumeMounts:
     - name: nginx-logs
       mountPath: /mnt/nginx-logs
 volumes:
  - name: nginx-logs
    emptyDir: 
     sizeLimit: 500Mi