apiVersion: v1
kind: PersistentVolume
metadata:
 name: ebc-static-pv
spec:
 accessModes:
  - ReadWriteMany
 capacity:
  storage: 5Gi
 csi:
  driver: efs.csi.aws.com
  fsType: efs
  volumeHandle: fs-08be3ce021b4e2788
