apiVersion: apps/v1
kind: Deployment 
metadata:
 name: nginx-deployment 
 labels:
  project: roboshop 
  #purpose: deployment-demo
  tier: frontend
  component: frontend 
 annotations:
    kubernetes.io/change-cause: "moving to 1.29"
spec:
 replicas: 2
 selector:
  matchLabels:
   project: roboshop
   purpose: deployment-demo
   tier: frontend
   component: frontend 
 template:
  metadata:
   name: nginx-deployment-pod 
   labels:
    project: roboshop 
    purpose: deployment-demo
    tier: frontend
    component: frontend 
  spec:
   containers:
    - name: nginx 
      image: nginx:1.29