apiVersion: apps/v1
kind: Deployment 
metadata:
 name: nginx-deployment 
 labels:
  project: roboshop 
  #purpose: deployment-demo
  tier: frontend
  component: frontend 
 annotations:
    kubernetes.io/change-cause: "moving to 1.29"
spec:
 replicas: 3
 selector:
  matchLabels:
   project: roboshop
   purpose: deployment-demo
   tier: frontend
   component: frontend 
 template:
  metadata:
   name: nginx-deployment-pod 
   labels:
    project: roboshop 
    purpose: deployment-demo
    tier: frontend
    component: frontend 
  spec:
   containers:
    - name: nginx 
      image: nginx:1.29
---
apiVersion: v1
kind: Service
metadata:
 name: nginx
spec:
 type: ClusterIP
 selector:
  project: roboshop
  tier: frontend
  component: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-headless
spec:
 clusterIP: none
 selector:
  project: roboshop
  tier: frontend
  component: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80
 